### ISSUE TITLE
Ошибочка -_-

### ISSUE THREAD

**Issue by FO1ZZY** [minjidays/minji-sound#2]
// LOG DISCORD
AttributeError("'Track' object has no attribute 'download_bytes_async'") 

// LOG CONSOLE PYCHARM

C:\Users\vwrps\OneDrive\Рабочий стол\music-bot-master\venv\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\vwrps\OneDrive\Рабочий стол\music-bot-master\cogs\music.py", line 548, in p
    songs = await self.search_ym(query, inter, self.bot) # Ищем по названию или берём из ссылки трек в яндекс музыке
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vwrps\OneDrive\Рабочий стол\music-bot-master\cogs\music.py", line 456, in search_ym
    await downloadFirstYM(data)
  File "C:\Users\vwrps\OneDrive\Рабочий стол\music-bot-master\cogs\music.py", line 58, in downloadFirstYM
    await loop.run_in_executor(ThreadPoolExecutor(), trackCompression)
  File "C:\Users\vwrps\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vwrps\OneDrive\Рабочий стол\music-bot-master\cogs\music.py", line 54, in trackCompression
    audio_data = AudioSegment.from_file(BytesIO(trackSource), format='mp3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vwrps\OneDrive\Рабочий стол\music-bot-master\venv\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vwrps\OneDrive\Рабочий стол\music-bot-master\venv\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vwrps\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\vwrps\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Не удается найти указанный файл

**Comment by celedriel** [comment]
hey man, first of all, I am SO sorry for the massive delay! It's been literally over two years LMAO 💀 I hope you're still alive and not still waiting for this bot to run...

**1. the `FileNotFoundError: [WinError 2]` (couldn't find ffprobe)**
your windows system doesn't have FFmpeg installed. you just need to download FFmpeg for windows, grab the `ffmpeg.exe` and `ffprobe.exe` files from the extracted `bin` folder, and drop them directly into the bot's root directory. the `pydub` library needs them to read the mp3 in memory.

**2. the `AttributeError: 'Track' object has no attribute 'download_bytes_async'`**
the `yandex-music` library got updated and changed how this works. since your code is already running the audio compression inside a `loop.run_in_executor()`, you don't even need the async version of that method.
Just go to `cogs/music.py` and change:
`track.download_bytes_async()`
to the synchronous version:
`track.download_bytes()`

again, my bad for taking literally years to reply. better late than never!

**Comment by FO1ZZY** [comment]
Thank you, my friend, for your reply. I don’t know what I’d do without you. Much love, brother. 🤜🤛
